default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: giga_challenge_development

test:
  <<: *default
  database: giga_challenge_test

production:
  <<: *default
  database: giga_challenge_production
  username: giga_challenge
  password: <%= ENV['GIGA_CHALLENGE_DATABASE_PASSWORD'] %>
